server:
  port: 8080
# 配置数据库连接 url中的orcl可以理解为库的名称
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: wzc
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
# 设置mybatis扫描.xml文件的路径以及配置打印
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true # 驼峰命名
# 设置日志打印
logging:
  level:
    mapper: debug
